version: '3.2'
services:
  jenkins:
    image: jenkins-docker
    build: ./jenkins
    restart: unless-stopped
    ports:
      - 8081:8080
    volumes:
      - ./jenkins/data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: jenkins-docker
  sonarqube:
    image: sonarqube:6.7.5-alpine
    container_name: sonarqube
    ports:
      - 8080:9000
      - 9092:9092
    volumes:
      - ./sonarqube/config:/opt/sonarqube/conf
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/extensions:/opt/sonarqube/extensions
      - ./sonarqube/plugins:/opt/sonarqube/lib/bundled-plugins
  
        

